# Pacakges used
```{r}
library(Seurat)
library(ggplot2)
library(monocle3)
library(SeuratWrappers)
library(gridExtra)
```

# Trajectory Inference
```{r}
# Read in and prepare data
uRA4.1 = readRDS("data/uRA4_w_subs.rds")
uRA4_traj = as.cell_data_set(uRA4.1) # Convert to cell dataset

# Extract cluster information from Seurat object
recreate.partition = c(rep(1, length(uRA4_traj@colData@rownames)))
names(recreate.partition) = uRA4_traj@colData$rownames
recreate.partition = as.factor(recreate.partition)
uRA4_traj@clusters$UMAP$UMAP$clusters = list_cluster

## Assign cluster information
list_cluster = uRA4.1@active.ident
uRA4_traj@reductions$umap@cell.embeddings

## Assign UMAP coordinate cell embeddings
uRA4_traj@int_colData@listData$reducedDims$UMAP = 
  uRA4.1@reductions$umap@cell.embeddings

# Learn trajectory graph
uRA4_traj = learn_graph(uRA4_traj, use_partition = T)

plot_cells(uRA4_traj, 
           color_cells_by = "cluster", 
           label_groups_by_cluster = F, 
           group_label_size = 7, 
           cell_size = 2, 
           trajectory_graph_segment_size = 1.5, 
           trajectory_graph_color = "black") # Plot trajectory

# Pseudo-temporal ordering of cells
uRA4_traj = order_cells(uRA4_traj) # Select node in cluster 0 (unswitched MBCs)

plot_cells(uRA4_traj, 
           color_cells_by = "pseudotime", 
           label_groups_by_cluster = T, 
           group_label_size = 7, 
           cell_size = 2, 
           trajectory_graph_segment_size = 1.5, 
           trajectory_graph_color = "black") # Plot trajectory with cells colored by pseudotime
```
